#!/bin/bash
home=~
here=`pwd`
dryrun=
ignore='(^\.$|^\.\.$|^\.git$|^[^\.]|~$)'

i=0
commands=()
for f in $(ls -a 2>/dev/null); do
	if [[ $f =~ $ignore ]]; then
		continue
	fi
	if [ -h ~/$f ]; then
		echo "skipping $f it's already a symbolic link"
		continue
	fi
	if [ -e ~/$f ]; then
		commands[$i]="cp -R $home/$f $here/$f"
		let i++
		commands[$i]="rm -rf $home/$f"
		let i++
		
	fi
	commands[$i]="ln -sf $here/$f $home/$f"
	let i++
done

for ((j=0;j<$i;j++)) do
	echo ${commands[$j]}
	if [ -z $dryrun ]; then
		continue
	fi
	${commands[$j]}
done
